### ISSUE TITLE
自定义查询 - 查询多列的时候如何返回？List<Map>吗？

### ISSUE THREAD

**Issue by Jackeylou** [biezhi/anima#18]
![image](https://user-images.githubusercontent.com/3167733/39350028-8b60428c-4a2f-11e8-9971-8ecd3c38956d.png)

**Comment by biezhi** [comment]
可以支持返回 `List<Map>`，在下个版本中加入它。

**Comment by biezhi** [comment]
[test code](https://github.com/biezhi/anima/blob/master/src/test/java/io/github/biezhi/anima/SelectTest.java#L214)
