### ISSUE TITLE
SqlServer2012以上可以使用offset-fetch翻页来提升性能

### ISSUE THREAD

**Issue by ydq** [biezhi/anima#19]
SqlServer2012及以上版本可以使用offset-fetch翻页来提升性能，最终的sql可以如下
```sql
select * from table 
where column = ? 
order by current_timestamp -- 注1
offset ? rows fetch next ? rows only
```
注1：如果用户的sql没有order by，offset必须要在order by后面，因此可以添加一个根据时间戳order by，如果用户的sql有order by，则无需为其再添加order by

---

另外发现目前的`SqlServerDialect`分页是有bug的，生成出来的分页sql运行不通过，如果我没测试错的话。
```java
StringBuilder sql = new StringBuilder();
sql.append("SELECT * FROM ( SELECT row_number() over (ORDER BY tempcolumn) temprownumber, * FROM ( SELECT top ")
        .append(end)
        .append(" tempcolumn=0,")
        .append(select(sqlParams))
        .append(")vip)mvp where temprownumber>")
        .append(begin);
```

- `append(select(sqlParams))`这行，因为内置`select(sqlParams)`函数拼接出来的sql是带有select开头的，导致这里最终拼接出来的sql语句错误
- `append(")vip)mvp where temprownumber>")`这行，最后的应该是`>=`
- sqlserver带有distinct的语句（比如自定义sql的分页），top要放在distinct后面
- 最外层的`row_number() over (ORDER BY tempcolumn)`可以基于`current_timestamp`来排序，无需在内层多添加一列常量列，即：`row_number() over (ORDER BY current_timestamp)`

**Comment by biezhi** [comment]
感谢你的建议，下个版本会优化这块。
