### ISSUE TITLE
希望Anima的Model添加对枚举的自动映射支持

### ISSUE THREAD

**Issue by ydq** [biezhi/anima#22]
如题，希望Model添加对枚举的自动映射支持，允许通过注解等方式指定映射枚举哪个属性（或者直接toString或者索引值ordinal）映射数据库的字段

伪代码：

```java
public enum Gender{
        M,F;
}

public enum VipLevel{
        VIP1(1,"初级会员"),
        VIP2(2,"高级会员"),
        VIP3(3,"至尊会员");
 
        private int code;
        private String desc;
        //Getter Setter Constructor
}

@Table(name="`user`")
public class User extends Model{
        @EnumMapping(EnumMapping.TO_STRING)//映射数据库转换的时候直接调用toString()
        private Gender gender;
        @EnumMapping("code")//映射数据库转换的时候调用getCode()方法获取code值
        private VipLevel vipLevel;
}


public @interface EnumMapping {
    //预设 调用枚举的toString方法
    String TO_STRING = "toString";
    //预设 调用枚举的ordinal方法
    String ORDINAL = "ordinal";
    //默认是直接调用toString方法
    String value() default TO_STRING;
}
```

**Comment by biezhi** [comment]
[test code](https://github.com/biezhi/anima/blob/master/src/test/java/io/github/biezhi/anima/EnumTest.java)

**Comment by ydq** [comment]
看了下代码：
![image](https://user-images.githubusercontent.com/8097340/42490899-13d9e088-8445-11e8-992b-b39097a33745.png)
**[AnimaUtils](https://github.com/biezhi/anima/blob/master/src/main/java/io/github/biezhi/anima/utils/AnimaUtils.java#L108)** 中针对枚举只做了toString() 和 ordinal() 的处理，还可以针对属性做处理，例如：
~~~java
enum TYPE{
    TYPE_1(10,"this is type 1"),
    TYPE_2(20,"this is type 2"),
    TYPE_3(30,"this is type 3");

    private Integer code;
    private String desc;
// getter setter constructor 略..
}

class Pojo{
    @EnumMapping("code")
    TYPE type;
}
~~~
上例中：当我注解 @EnumMapping("code") ，则希望Anima能自动调用 type.getCode() 来获取值 存入数据库，注解中的内容是枚举的某个属性的field，然后根据这个枚举的field值来进行映射

> 因为ordinal 是类似于索引，当枚举取值的顺序变动的时候 ordinal 值会变，如果是一个可能会变的枚举，如不定期添加类型的枚举，可能某些时候不适合用ordinal，然后数据库为了存储效率也没用String

**Comment by biezhi** [comment]
我有一个简单的想法，把枚举作为类似于 `K/V` 来映射一个数据库操作，使用者需要遵循一种约定，所有的枚举只有2个成员：`K`  是数据库存储的值，`V` 是字符串类型的描述。格式如下：

```java
public enum PayTypeEnum {
   
    WAIT_PAY(100, "等待支付"),    
    PAY_SUCCESS(200, "支付成功");

    private Integer type;
    private String desc;

    PayTypeEnum(Integer type, String desc) {
        this.type = type;
        this.desc = desc;
    }
    
    // getter setter 省略
}
```

在 `Model` 中使用直接用枚举类型，不用添加注解配置了。

**为什么要约定死格式？**

Java 语言中使用枚举主要是为了方便其他的代码确定具体类型，我们为了在数据库操作时省去 `列值` 转换到枚举的这步操作使用了如上方式；而大部分的场景就是上述例子中的样子，只是 `type` 的类型可能不是 `Integer`。

假设不约定格式，也就是可以自定义。会出现几个问题 

1. 使用者要添加注解 
2. 框架内部在处理的时候不知道有几个成员(属性)，因为从数据库到枚举的过程是要构造一个枚举对象的

手动指定的方式和约定其实都会产生学习成本，只不过后者写的代码少，出错率也会低一些，个人见解。
