### ISSUE TITLE
PostgreSQL 分页

### ISSUE THREAD

**Issue by fanlide** [biezhi/anima#23]
PostgreSQL 不支持 LIMIT #,# 语法，如何变成LIMIT # OFFSET # 语法？

**Comment by ydq** [comment]
看了下 [PostgreSQLDialect](https://github.com/biezhi/anima/blob/master/src/main/java/io/github/biezhi/anima/dialect/PostgreSQLDialect.java) 是空的，应该是没完善 或者 你可以自己参考[MySQLDialect](https://github.com/biezhi/anima/blob/master/src/main/java/io/github/biezhi/anima/dialect/MySQLDialect.java)，写一个自己的方言，然后注入给Anima即可。

**Comment by biezhi** [comment]
https://github.com/biezhi/anima/pull/25
