### ISSUE TITLE
继承了Model的类无法使用Gson转换为JSON

### ISSUE THREAD

**Issue by swjtuhyq** [biezhi/anima#44]

**Comment by swjtuhyq** [comment]
我的Model是这样的：
@Table(name = "test")
@Data
public class Test extends Model{
    private int id;
    private int flag;
}

转Json是这样的：
Test test = new Test();
        test.setId(199);
        test.setFlag(13);
        String s = new Gson().toJson(test);
错误如下：
java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: com.robelf.appstore.model.Test. Forgot to register a type adapter?

这是什么原因呢，需要怎么设置才能使用呢？

**Comment by biezhi** [comment]
这是继承导致的序列化问题，已经修复了，在 `0.2.6` 版本中正常。

**Comment by swjtuhyq** [comment]
Dear biezhi,
	您好，谢谢您的回复！
